name: managment-center-build

on:
  push:
    branches:
      - master
env:
  TZ: 'Asia/Taipei'

jobs:
  build:
    runs-on: ubuntu-16.04
    name: Deploy Hexo Blog
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true # Checkout private submodules(themes or something else).
    - name: Timezone set Asia/Taipei
      run: sudo timedatectl set-timezone 'Asia/Taipei'
    - name: Yarn Install
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    - name: Hexo Deploy
      id: deploy
      uses: sma11black/hexo-action@v1.0.4
      with:
        deploy_key: ${{ secrets.DEPLOY_BLOG_KEY }}
        # user_name: <YOUR_GITHUB_USERNAME>  # (or delete this input setting to use bot account)
        # user_email: <YOUR_GITHUB_EMAIL>    # (or delete this input setting to use bot account)
    - name: Get the output
      run: |
        echo "${{ steps.deploy.outputs.notify }}"