name: managment-center-build

on:
  push:
    branches:
      - master

jobs:
  generate-static-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: unlock-keychain-db
        run: |
          yarn install
          npx hexo generate

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Build and push Docker image
      #   id: push
      #   uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      #   with:
      #     context: ./pkg/${{ env.IMAGE_NAME }}/
      #     file: ./pkg/${{ env.IMAGE_NAME }}/Dockerfile
      #     push: true
      #     tags: passon/${{ env.IMAGE_NAME }}:latest
  